### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-opencx

on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      TAP_INTERCOM_ACCESS_TOKEN: ${{secrets.TAP_INTERCOM_ACCESS_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
